### ISSUE TITLE
Getting occasionally  'other was less than the current instant' in Timeout middleware

### ISSUE THREAD

**Issue by shisoft** [tokio-rs/tokio-middleware#2]
I am trying to add request/response timeout for TcpClient. My implementation is shown below

```
    pub fn connect_with_timeout (address: &String, timeout: Duration) -> io::Result<Client> {
        let mut core = Core::new()?;
        let address = address.parse().unwrap();
        let future = Box::new(TcpClient::new(BytesClientProto)
                                  .connect(&address, &core.handle())
                                  .map(|c| Timeout::new(
                                      ClientCore {
                                          inner: c,
                                      },
                                      Timer::default(),
                                      timeout)));
        let client = core.run(future)?;
        Ok(Client {
            client: client,
            core: Box::new(core),
        })
    }
```

The error seems panicked from `tokio_time`, not sure if it is because I didn't use it right.

```
stack backtrace:
   1:     0x7f4f85da9c2c - std::sys::imp::backtrace::tracing::imp::write::h2a972e172776bc73
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f4f85db7f5e - std::panicking::default_hook::{{closure}}::h3350be9abe4c8496
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f4f85db7b64 - std::panicking::default_hook::h255964940ef72e84
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x7f4f85db8407 - std::panicking::rust_panic_with_hook::ha02a85ff57cdb669
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f4f85db8294 - std::panicking::begin_panic::hd282678ae37b0eee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7f4f85da5820 - <std::time::Instant as core::ops::Sub>::sub::he30b60fd7a8aab38
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/time.rs:276
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:714
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/time.rs:275
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/time/mod.rs:143
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/time/mod.rs:208
   7:     0x5619854cb7e7 - tokio_timer::worker::run::h1784171f754e877f
                        at /home/shisoft/.cargo/git/checkouts/tokio-timer-d282e7d6c658dca8/4acaed6/src/worker.rs:170
   8:     0x5619854c9c03 - tokio_timer::worker::Worker::spawn::{{closure}}::h5b11fa2442eb3044
                        at /home/shisoft/.cargo/git/checkouts/tokio-timer-d282e7d6c658dca8/4acaed6/src/worker.rs:64
   9:     0x5619854c056f - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::hfebfd6a327f96b86
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
  10:     0x5619854b3a6a - std::panicking::try::do_call::h58acbe5fbbeb3eb6
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  11:     0x7f4f85dc126a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  12:     0x5619854b3575 - std::panicking::try::h5e5bb5f8361aec88
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
  13:     0x5619854b2249 - std::panic::catch_unwind::he6601d08a33dd185
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
  14:     0x5619854b30d7 - std::thread::Builder::spawn::{{closure}}::h828d914eb25efe61
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:302
  15:     0x5619854bbe99 - <F as alloc::boxed::FnBox<A>>::call_box::hb4d683a80c5acbbd
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  16:     0x7f4f85db6dc4 - std::sys::imp::thread::Thread::new::thread_start::h27fa49fe81f658e4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
```

Any clues are welcome.

**Comment by carllerche** [comment]
Probably related to https://github.com/tokio-rs/tokio-timer/issues/7.

**Comment by shisoft** [comment]
They have different messages but point to the same line. I will close this issue if the problem is fixed. Thanks for the heads up.

**Comment by carllerche** [comment]
I resolved the bug on master. Could you see if you still hit the problem?

**Comment by shisoft** [comment]
Hi, I was trying to update my code to suit the newest tokio commit. But cannot compile at proto#d105efa8 and timer#c933447f.
I update the cargoes again afterwards to #d53f6c77 and #3c53ecb6, and failed to compile in tokio-middleware.
```
error[E0243]: wrong number of type arguments: expected 1, found 0
  --> /home/shisoft/.cargo/git/checkouts/tokio-middleware-84380a4401d2d7c0/e894dab/src/timeout.rs:29:19
   |
29 |           E: From<timer::TimeoutError>,
   |                   ^^^^^^^^^^^^^^^^^^^ expected 1 type argument

error: aborting due to previous error

error: Could not compile `tokio-middleware`
```
I suppose the new commit break the compile. Can you fix that?

Thank you for the efforts.

**Comment by shisoft** [comment]
Beware it is also failed in the CI https://travis-ci.org/tokio-rs/tokio-middleware/jobs/191406186

**Comment by carllerche** [comment]
Ah yes, the repo needs to track the tokio-timer changes... sorry about that.

**Comment by carllerche** [comment]
This should be fixed.

**Comment by shisoft** [comment]
The middleware compiled. However I still getting some difficulties in updating my own code. Not sure if it is from your side or mine.

I know here may not be the suitable place to ask such questions, but I just cannot find out the reason and their solution since I updated to the last commit. My version to rustc is `rustc 1.16.0-nightly (1a2ed98d3 2017-01-13)`. It will be great if you can simply take a look at them. If you want to read the code please go to https://github.com/shisoft/bifrost

The first one is from initializing `Timeout`
```
error[E0308]: mismatched types
  --> src/tcp/client.rs:51:39
   |
51 |                                       Timer::default(),
   |                                       ^^^^^^^^^^^^^^^^ expected struct `tokio_timer::timer::Timer`, found struct `tokio_timer::Timer`
   |
   = note: expected type `tokio_timer::timer::Timer`
   = note:    found type `tokio_timer::Timer`
```
I added `use tokio_timer::Timer;` for the default function like what you did in the tests (https://github.com/tokio-rs/tokio-middleware/blob/master/tests/test_timeout.rs), but the compiler complain about the mismatched type shown before. `tokio_timer::timer::Timer` is a private module, so it cannot been used.


Another is more weird, I already added `use tokio_service::Service;` in the module but the compiler still told me to use it
```
error: no method named `call` found for type `tokio_proto::multiplex::ClientService<tokio_core::net::TcpStream, tcp::proto::BytesClientProto>` in the current scope
  --> src/tcp/client.rs:37:20
   |
37 |         self.inner.call(req).boxed()
   |                    ^^^^
   |
   = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
   = help: candidate #1: `use tokio_service::Service;`
```

The last one is also about `tokio_service::Service`. My service already `impl` tokio_service::Service. But the compiler said not
```
error[E0277]: the trait bound `tcp::server::Server: tokio_service::Service` is not satisfied
  --> src/tcp/server.rs:32:48
   |
32 |         TcpServer::new(BytesServerProto, addr).serve(move || {
   |                                                ^^^^^ the trait `tokio_service::Service` is not implemented for `tcp::server::Server`
   |
   = note: required because of the requirements on the impl of `tokio_service::NewService` for `[closure@src/tcp/server.rs:32:54: 36:10 callback:_]`
```

**Comment by shisoft** [comment]
I will close this issue because I found the solution for the compile problem.
Someone told me that tokio core and most of it's components have already uploaded to crate.io, which means I should use those instead of unstable git as up stream. Maybe @carllerche can update the readme for them in the `Usage` sections?

The issue from `time` seems gone already. Many thanks for the fix.
